/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowingsRouteImport } from './routes/showings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as MatchRouteImport } from './routes/match'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DealRouteImport } from './routes/deal'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ClientRouteImport } from './routes/client'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealIndexRouteImport } from './routes/deal.index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as DealPaymentRouteImport } from './routes/deal.payment'
import { Route as DealFormsRouteImport } from './routes/deal.forms'
import { Route as DealCompleteRouteImport } from './routes/deal.complete'
import { Route as DealAcceptanceRouteImport } from './routes/deal.acceptance'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'

const ShowingsRoute = ShowingsRouteImport.update({
  id: '/showings',
  path: '/showings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DealRoute = DealRouteImport.update({
  id: '/deal',
  path: '/deal',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealIndexRoute = DealIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DealRoute,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DealPaymentRoute = DealPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => DealRoute,
} as any)
const DealFormsRoute = DealFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => DealRoute,
} as any)
const DealCompleteRoute = DealCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => DealRoute,
} as any)
const DealAcceptanceRoute = DealAcceptanceRouteImport.update({
  id: '/acceptance',
  path: '/acceptance',
  getParentRoute: () => DealRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/clients': typeof ClientsRouteWithChildren
  '/deal': typeof DealRouteWithChildren
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/offer': typeof OfferRoute
  '/search': typeof SearchRoute
  '/showings': typeof ShowingsRoute
  '/clients/$id': typeof ClientsIdRoute
  '/deal/acceptance': typeof DealAcceptanceRoute
  '/deal/complete': typeof DealCompleteRoute
  '/deal/forms': typeof DealFormsRoute
  '/deal/payment': typeof DealPaymentRoute
  '/property/$id': typeof PropertyIdRoute
  '/deal/': typeof DealIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/clients': typeof ClientsRouteWithChildren
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/offer': typeof OfferRoute
  '/search': typeof SearchRoute
  '/showings': typeof ShowingsRoute
  '/clients/$id': typeof ClientsIdRoute
  '/deal/acceptance': typeof DealAcceptanceRoute
  '/deal/complete': typeof DealCompleteRoute
  '/deal/forms': typeof DealFormsRoute
  '/deal/payment': typeof DealPaymentRoute
  '/property/$id': typeof PropertyIdRoute
  '/deal': typeof DealIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client': typeof ClientRoute
  '/clients': typeof ClientsRouteWithChildren
  '/deal': typeof DealRouteWithChildren
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/offer': typeof OfferRoute
  '/search': typeof SearchRoute
  '/showings': typeof ShowingsRoute
  '/clients/$id': typeof ClientsIdRoute
  '/deal/acceptance': typeof DealAcceptanceRoute
  '/deal/complete': typeof DealCompleteRoute
  '/deal/forms': typeof DealFormsRoute
  '/deal/payment': typeof DealPaymentRoute
  '/property/$id': typeof PropertyIdRoute
  '/deal/': typeof DealIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client'
    | '/clients'
    | '/deal'
    | '/login'
    | '/match'
    | '/offer'
    | '/search'
    | '/showings'
    | '/clients/$id'
    | '/deal/acceptance'
    | '/deal/complete'
    | '/deal/forms'
    | '/deal/payment'
    | '/property/$id'
    | '/deal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client'
    | '/clients'
    | '/login'
    | '/match'
    | '/offer'
    | '/search'
    | '/showings'
    | '/clients/$id'
    | '/deal/acceptance'
    | '/deal/complete'
    | '/deal/forms'
    | '/deal/payment'
    | '/property/$id'
    | '/deal'
  id:
    | '__root__'
    | '/'
    | '/client'
    | '/clients'
    | '/deal'
    | '/login'
    | '/match'
    | '/offer'
    | '/search'
    | '/showings'
    | '/clients/$id'
    | '/deal/acceptance'
    | '/deal/complete'
    | '/deal/forms'
    | '/deal/payment'
    | '/property/$id'
    | '/deal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientRoute: typeof ClientRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DealRoute: typeof DealRouteWithChildren
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  OfferRoute: typeof OfferRoute
  SearchRoute: typeof SearchRoute
  ShowingsRoute: typeof ShowingsRoute
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showings': {
      id: '/showings'
      path: '/showings'
      fullPath: '/showings'
      preLoaderRoute: typeof ShowingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal': {
      id: '/deal'
      path: '/deal'
      fullPath: '/deal'
      preLoaderRoute: typeof DealRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal/': {
      id: '/deal/'
      path: '/'
      fullPath: '/deal/'
      preLoaderRoute: typeof DealIndexRouteImport
      parentRoute: typeof DealRoute
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal/payment': {
      id: '/deal/payment'
      path: '/payment'
      fullPath: '/deal/payment'
      preLoaderRoute: typeof DealPaymentRouteImport
      parentRoute: typeof DealRoute
    }
    '/deal/forms': {
      id: '/deal/forms'
      path: '/forms'
      fullPath: '/deal/forms'
      preLoaderRoute: typeof DealFormsRouteImport
      parentRoute: typeof DealRoute
    }
    '/deal/complete': {
      id: '/deal/complete'
      path: '/complete'
      fullPath: '/deal/complete'
      preLoaderRoute: typeof DealCompleteRouteImport
      parentRoute: typeof DealRoute
    }
    '/deal/acceptance': {
      id: '/deal/acceptance'
      path: '/acceptance'
      fullPath: '/deal/acceptance'
      preLoaderRoute: typeof DealAcceptanceRouteImport
      parentRoute: typeof DealRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface DealRouteChildren {
  DealAcceptanceRoute: typeof DealAcceptanceRoute
  DealCompleteRoute: typeof DealCompleteRoute
  DealFormsRoute: typeof DealFormsRoute
  DealPaymentRoute: typeof DealPaymentRoute
  DealIndexRoute: typeof DealIndexRoute
}

const DealRouteChildren: DealRouteChildren = {
  DealAcceptanceRoute: DealAcceptanceRoute,
  DealCompleteRoute: DealCompleteRoute,
  DealFormsRoute: DealFormsRoute,
  DealPaymentRoute: DealPaymentRoute,
  DealIndexRoute: DealIndexRoute,
}

const DealRouteWithChildren = DealRoute._addFileChildren(DealRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientRoute: ClientRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DealRoute: DealRouteWithChildren,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  OfferRoute: OfferRoute,
  SearchRoute: SearchRoute,
  ShowingsRoute: ShowingsRoute,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
