/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YieldMapRouteImport } from './routes/yield-map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProspectusRouteImport } from './routes/prospectus'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'

const YieldMapRoute = YieldMapRouteImport.update({
  id: '/yield-map',
  path: '/yield-map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectusRoute = ProspectusRouteImport.update({
  id: '/prospectus',
  path: '/prospectus',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/communities': typeof CommunitiesRoute
  '/crm': typeof CrmRoute
  '/prospectus': typeof ProspectusRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/yield-map': typeof YieldMapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/communities': typeof CommunitiesRoute
  '/crm': typeof CrmRoute
  '/prospectus': typeof ProspectusRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/yield-map': typeof YieldMapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/communities': typeof CommunitiesRoute
  '/crm': typeof CrmRoute
  '/prospectus': typeof ProspectusRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/yield-map': typeof YieldMapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/communities'
    | '/crm'
    | '/prospectus'
    | '/reports'
    | '/settings'
    | '/yield-map'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/communities'
    | '/crm'
    | '/prospectus'
    | '/reports'
    | '/settings'
    | '/yield-map'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/communities'
    | '/crm'
    | '/prospectus'
    | '/reports'
    | '/settings'
    | '/yield-map'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  CommunitiesRoute: typeof CommunitiesRoute
  CrmRoute: typeof CrmRoute
  ProspectusRoute: typeof ProspectusRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  YieldMapRoute: typeof YieldMapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yield-map': {
      id: '/yield-map'
      path: '/yield-map'
      fullPath: '/yield-map'
      preLoaderRoute: typeof YieldMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospectus': {
      id: '/prospectus'
      path: '/prospectus'
      fullPath: '/prospectus'
      preLoaderRoute: typeof ProspectusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  CommunitiesRoute: CommunitiesRoute,
  CrmRoute: CrmRoute,
  ProspectusRoute: ProspectusRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  YieldMapRoute: YieldMapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
